server:
  port: 8088
  servlet:
    context-path: /blog

#加密
jasypt:
  encryptor:
    password: mineblog

#数据库配置wtxyp%Coi8pA
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.119.123.56:3306/blog?usessl = false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1qaz@WSX3edc
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #热部署
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  data:
    elasticsearch:
      repositories:
        enabled: true
  redis:
    host: r-uf66vjadwn625cc6y3pd.redis.rds.aliyuncs.com
    port: 6379
    password: 1qaz@WSX
    timeout: 3000
    database: 0
    lettuce:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 20
        min-idle: 0


#日志配置
logging:
  level:
    # root日志以WARN级别输出
    root: info
    # 此包下所有class以DEBUG级别输出
    com.munjie.blog.dao: debug

#文件目录
logpath: D:/BLOG_LOG/


#
#Elasticsearch配置
elasticsearch:
  host: 47.119.123.56
  port: 9300
  clustername: elasticsearch
  poolsize: 5

#百度地图算路配置
baidu:
  originAdd: 无锡江阴市亚包大道199号
  key: ihobW2ZNw3i96MOadGGRx2BN7pjxX3bQ
  geocoding: https://api.map.baidu.com/geocoding/v3/?address=
  routematrix: https://api.map.baidu.com/routematrix/v2/driving
  logisticsRoutematrix: https://api.map.baidu.com/logistics_routematrix/v1/truck


