spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.munjie.blog.pojo

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check